name: example-python-workflow
run-name: ${{ github.actor }} is trying out GitHub Actions!
on: [ push ]
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Install Python 3.12
            uses: actions/setup-python@v5
            with:
                python-version: "3.12"
          - name: Say hi
            run: python -c "print( \"Hello, ${{ github.actor }}!\" )"
            